"use client";

import { Card, CardHeader } from "@/components/ui/Card";
import { StatusPill } from "@/components/ui/StatusPill";

interface Props {
  recommendation: string;
  sourceGroundingSummary: string;
  nextActions: string[];
  toolCallCount: number;
  model: string;
}

export function ExecutiveRecommendation({
  recommendation,
  sourceGroundingSummary,
  nextActions,
  toolCallCount,
  model,
}: Props) {
  return (
    <Card>
      <CardHeader
        title="Executive Recommendation"
        subtitle="Generated by Claude tool-use loop · server-side"
        right={
          <div className="flex items-center gap-2">
            <StatusPill label={`${toolCallCount} tools`} tone="info" />
            <StatusPill label={model || "Claude"} tone="neutral" />
          </div>
        }
      />
      {recommendation ? (
        <p className="text-[14px] text-ink leading-relaxed max-w-3xl">
          {recommendation}
        </p>
      ) : (
        <p className="text-[13px] text-muted">
          Run the mission readiness analysis to generate Claude&rsquo;s
          executive recommendation.
        </p>
      )}
      {sourceGroundingSummary ? (
        <p className="text-[12px] text-muted mt-4">
          <span className="font-medium text-ink">Source grounding:</span>{" "}
          {sourceGroundingSummary}
        </p>
      ) : null}
      {nextActions.length > 0 ? (
        <div className="mt-4">
          <div className="text-[10px] uppercase tracking-[0.14em] text-muted mb-2">
            Next actions
          </div>
          <ul className="text-[13px] text-ink list-disc pl-5 space-y-1">
            {nextActions.map((a, i) => (
              <li key={i}>{a}</li>
            ))}
          </ul>
        </div>
      ) : null}
    </Card>
  );
}
